export default [
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
    {
        name: 'Довод',
        genres: ['Боевик', 'Триллер'],
        iconUrl: 'https://www.kino-teatr.ru/movie/posters/big/2/136612.jpg',
        id: 1,
        releaseDate: new Date().getFullYear(),
        tagline: 'Время уходит',
        budget: '$500000000',
    },
]
